type: postgres
tables:
- name: test
  columns:
  - name: id
    type: integer
    is_primary_key: true
    optional: false
    referenced_by: []
    references: null
  - name: name
    type: text
    is_primary_key: false
    optional: false
    referenced_by: []
    references: null
- name: user
  columns:
  - name: id
    type: uuid
    is_primary_key: true
    optional: false
    referenced_by:
    - table: test
      column: user_id
    - table: _user_account
      column: user_id
    references: null
  - name: email
    type: text
    is_primary_key: false
    optional: false
    referenced_by: []
    references: null
  - name: password
    type: character varying
    is_primary_key: false
    optional: false
    referenced_by: []
    references: null
- name: _user_account
  columns:
  - name: user_id
    type: uuid
    is_primary_key: true
    optional: false
    referenced_by: []
    references:
      table: user
      column: id
  - name: account_id
    type: uuid
    is_primary_key: true
    optional: false
    referenced_by: []
    references:
      table: account
      column: id
- name: account
  columns:
  - name: id
    type: uuid
    is_primary_key: true
    optional: false
    referenced_by:
    - table: _user_account
      column: account_id
    references: null
  - name: name
    type: text
    is_primary_key: false
    optional: false
    referenced_by: []
    references: null
